version: "3"
services:
  db:
    image: postgres:11.2-alpine
    expose:
      - "5432"
    environment:
      - TIMEZONE=Asis/Shanghai
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=tour
      - LANG=C.UTF-8

  service:
    image: "wzekin/bupt_tour"
    depends_on:
      - db
    ports:
      - "8000:8080"
    volumes:
      - ./logs:/App/logs
    environment:
      - LANG=C.UTF-8

  backend:
    image: "wzekin/backend-shahe-guide"
    depends_on:
      - db
    ports:
      - "4200:80"
